@url_dev = http://localhost:3044/v1/api

### sign up
POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: d22131361037905b74388a3215b5078b0de51a37c3190af24b973bcc4afc4b6e75b3ffeaea5e5fcd34245d8877df0eea20d43ab2c311bd7a530dc0a817df2afc

{
    "name" : "Shop QuangDev",
    "email" : "shopquangdev@gmail.com",
    "password" : "quang1235613123"
}

### login
POST {{url_dev}}/shop/login
Content-Type: application/json
x-api-key: d22131361037905b74388a3215b5078b0de51a37c3190af24b973bcc4afc4b6e75b3ffeaea5e5fcd34245d8877df0eea20d43ab2c311bd7a530dc0a817df2afc

{
    "email" : "shopquangdev@gmail.com",
    "password" : "quang1235613123"
}

### logout
POST {{url_dev}}/shop/logout
Content-Type: application/json
x-api-key: d22131361037905b74388a3215b5078b0de51a37c3190af24b973bcc4afc4b6e75b3ffeaea5e5fcd34245d8877df0eea20d43ab2c311bd7a530dc0a817df2afc
x-client-id: 6aa3cdd741b461cb1c3eeb68
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaG9wSWQiOiI2YWEzY2RkNzQxYjQ2MWNiMWMzZWViNjgiLCJlbWFpbCI6InNob3BxdWFuZ2RldkBnbWFpbC5jb20iLCJpYXQiOjE3ODkxMjA1NjEsImV4cCI6MTc4OTI5MzM2MX0.YtGZJKQTou4dqGL9hv6GrU_lTYLP8VmP5iVPGlpBEd9K8Sa5G6qYwmAZwRYTFwzxm-dqzRVPI7V9XBcdD3amdlAlp3DlJe-4W0CGEuJqqjJktEqn4UBQWBr7hpxwo7QSnxyYfrNZeyiTtxq16Ko0Ce_kYiyLgwyQgUikHJoFwuwi689PzBiacUFEdr9yb6XMJyq504QvOzLK4OT8RRuBobYDoHRL8gWgHjQVjUrTRBmmns-WL98D3S51dIGAjbzD5cakYOsiQQfF5VPumh4kZJMIlFQafFRyrT7G_T83QUGwys5yQOuhJsA1k7TwrBFvs0t-znmxhbJlmL12VMNFGes-t93wRLNSJpcTGB0y-LNVs0AxV2k46ZYvg6CXg3RpQa6z-xOd0dsMZiBbz0WIHr-SutEuQ6C3pNC3h_KistUrPKlEZrXE-lt-iMQvpN2yGZCtFyMGOcl9rClIwMMMocQXDDAe7ET9Vd-KOEklv3Pw3gKIoCW6OK-vyQEYxXveg5s6msU3zNVn3MuSTKyM3aoymMJumWDVz7bXG0bybauLBGQf3lnWc7NiN-s_E96ZekP21_pzbEiAXCqaZUr_4rwDfTKjTq5F-dsXU6NL70uVMy0iIq1sDdGVmC7f8hTxw3ogMtSgnhSpRfRUPpQPAZGM_vsa0XaSMBvaDrTNbRk

{
    "email" : "shopquangdev@gmail.com",
    "password" : "quang1235613123"
}

### handlerRefreshToken
POST {{url_dev}}/shop/handlerRefreshToken
Content-Type: application/json
x-api-key: d22131361037905b74388a3215b5078b0de51a37c3190af24b973bcc4afc4b6e75b3ffeaea5e5fcd34245d8877df0eea20d43ab2c311bd7a530dc0a817df2afc
x-client-id: 6aa3cdd741b461cb1c3eeb68
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaG9wSWQiOiI2YWEzY2RkNzQxYjQ2MWNiMWMzZWViNjgiLCJlbWFpbCI6InNob3BxdWFuZ2RldkBnbWFpbC5jb20iLCJpYXQiOjE3ODkxMjA0OTcsImV4cCI6MTc4OTI5MzI5N30.d1p7zlAFah7X1QtAu02aPzhjuEMWbWSEWXAUsj-03JYaA8Tj-HcpDR3-S0265eNdwLbzL2WczgaIyjPNd3ELkelYH7rKtPzotvCEi_ZNICueQ04-Q8MVR4qUHW92GO-0ojkvdvbtWxb6dq06HW-2RiPpQh1wpLfSwNUJjmaHA_g8lItx9oJxO0FE5SBPh6o-uv7l5nLMuzQlasG9EQEajKv5lIBOcFRmBx0qlB7fsVatKJuEZm5fK1g0y2r0ioq1gkjsr8N2YndyiIsvxfuqdm7azwgqsu2wGbi3MBSosDj09MfNebiu3YR3BRk2j6tcE1kwUlaLgfw4YtGBYwhdTFPqcW5JZ5zkZQ-nKz0UPsqFfbfA7VBy7MmbsKnEMmBQLEqNIe6XjdyVqdJ1c5OG9bTPwAd2HDLmrVRrgTig3P17sNBjOFKlNovz3qzoJyTlkoY30FvtKe8dQ8aCDg2lphhFJV4B-iQeUCFfoH0kcRHbHPWmHD-pRxCF7rA234k8K1SNVt6C2GgTHc9MrU7Zk5YNMRCg_9GZE21P6vqXFspd06_lauZeGuA7iRlIkjDWzXOiWABk1FJ7qOVDe2siMpn7NYDiocNeCdV3MfeH73sJraZpX4v0K2nly1sc0Vw71yrNoDQtF2yghUDwzCSEPGjlQT36ognVp7FpYQJpOsU

{
    "refreshToken" : "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaG9wSWQiOiI2YWEzY2RkNzQxYjQ2MWNiMWMzZWViNjgiLCJlbWFpbCI6InNob3BxdWFuZ2RldkBnbWFpbC5jb20iLCJpYXQiOjE3ODkxMjA0OTcsImV4cCI6MTc4OTcyNTI5N30.VK95RvJsAmp1ePZvOXzHQQgPz6tD1Q0cv4F1jckd4nvEK_WzBeFaMGJaS8-yL0WYYy36Pbu_SpU6d2T4gMQCW1gklia3jK4tNag31JK01cPX0jJTel9xrSjX45UhcmZkuNQ1qxZhe8IiaquGQbpg-Jyk4zuKf9D-3e2NyV86wkujvhtCuq-5oIZk1WS3nXkxbfgDgqvKRxenpMitdGYg2nmm-A9Xi0TRPdPSdUvFqv7H_iEZJLOZGHOE9br47zYatomS-YoR5uKW2MKioiMTWGoegQyXjFRfG3i0b99xRlu9ytbV8RO4c1Ns9gZ7nZ3Fa_MkAjBcuFcchPm0kJ_G1yukX7j1g2_apHJK3zusKc-KkZ0ozl6glkz29CEbg0Tuzbtj15w1Z9w4bCE1Woya6jvCtKQd9OHdT2gSE8DIWLeky40bFBDbw4Qd64EWE5qBLneSGFR_1Dn0MATAeDKn49-0elWuT7pSfz0dhI43xVmDM_1kXIrAT8Tg7RHyLmEiB7ekPrR1dTL2T8Ng76grxkpfzjXvFCXv0kzmGm-BizmSc8GzjFhvKY9JQBQw4fnAAhk73VnFJdPA9la10kpr_iiJAoO9QTyZrTiQP1dGXmqt2FUp3RX3oyDG0S5xRjzEdYP-RgNsTIgEByhyw0jnOe-u5Atq_5dLlLJY9fiPsgo"
}

