@url_dev = http://localhost:3044/v1/api

### sign up
POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: d22131361037905b74388a3215b5078b0de51a37c3190af24b973bcc4afc4b6e75b3ffeaea5e5fcd34245d8877df0eea20d43ab2c311bd7a530dc0a817df2afc

{
    "name" : "Shop QuangDev01",
    "email" : "shopquangdev01@gmail.com",
    "password" : "quang1235613123"
}

### login
POST {{url_dev}}/shop/login
Content-Type: application/json
x-api-key: d22131361037905b74388a3215b5078b0de51a37c3190af24b973bcc4afc4b6e75b3ffeaea5e5fcd34245d8877df0eea20d43ab2c311bd7a530dc0a817df2afc

{
    "email" : "shopquangdev@gmail.com",
    "password" : "quang1235613123"
}

### logout
POST {{url_dev}}/shop/logout
Content-Type: application/json
x-api-key: d22131361037905b74388a3215b5078b0de51a37c3190af24b973bcc4afc4b6e75b3ffeaea5e5fcd34245d8877df0eea20d43ab2c311bd7a530dc0a817df2afc
x-client-id: 6aa3cdd741b461cb1c3eeb68
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaG9wSWQiOiI2YWEzY2RkNzQxYjQ2MWNiMWMzZWViNjgiLCJlbWFpbCI6InNob3BxdWFuZ2RldkBnbWFpbC5jb20iLCJpYXQiOjE3ODkxMjA1NjEsImV4cCI6MTc4OTI5MzM2MX0.YtGZJKQTou4dqGL9hv6GrU_lTYLP8VmP5iVPGlpBEd9K8Sa5G6qYwmAZwRYTFwzxm-dqzRVPI7V9XBcdD3amdlAlp3DlJe-4W0CGEuJqqjJktEqn4UBQWBr7hpxwo7QSnxyYfrNZeyiTtxq16Ko0Ce_kYiyLgwyQgUikHJoFwuwi689PzBiacUFEdr9yb6XMJyq504QvOzLK4OT8RRuBobYDoHRL8gWgHjQVjUrTRBmmns-WL98D3S51dIGAjbzD5cakYOsiQQfF5VPumh4kZJMIlFQafFRyrT7G_T83QUGwys5yQOuhJsA1k7TwrBFvs0t-znmxhbJlmL12VMNFGes-t93wRLNSJpcTGB0y-LNVs0AxV2k46ZYvg6CXg3RpQa6z-xOd0dsMZiBbz0WIHr-SutEuQ6C3pNC3h_KistUrPKlEZrXE-lt-iMQvpN2yGZCtFyMGOcl9rClIwMMMocQXDDAe7ET9Vd-KOEklv3Pw3gKIoCW6OK-vyQEYxXveg5s6msU3zNVn3MuSTKyM3aoymMJumWDVz7bXG0bybauLBGQf3lnWc7NiN-s_E96ZekP21_pzbEiAXCqaZUr_4rwDfTKjTq5F-dsXU6NL70uVMy0iIq1sDdGVmC7f8hTxw3ogMtSgnhSpRfRUPpQPAZGM_vsa0XaSMBvaDrTNbRk

{
    "email" : "shopquangdev@gmail.com",
    "password" : "quang1235613123"
}

### handlerRefreshToken
POST {{url_dev}}/shop/handlerRefreshToken
Content-Type: application/json
x-api-key: d22131361037905b74388a3215b5078b0de51a37c3190af24b973bcc4afc4b6e75b3ffeaea5e5fcd34245d8877df0eea20d43ab2c311bd7a530dc0a817df2afc
x-client-id: 6aa3cdd741b461cb1c3eeb68
x-rtoken-id: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaG9wSWQiOiI2YWEzY2RkNzQxYjQ2MWNiMWMzZWViNjgiLCJlbWFpbCI6InNob3BxdWFuZ2RldkBnbWFpbC5jb20iLCJpYXQiOjE3OTAwNjExNjQsImV4cCI6MTc5MDY2NTk2NH0.DHKBgE1vyN3w8H2MksfjJv331z3VTpXxdzMaP2Xqt4nUc0jMicEShiujb-nUE4-1Nv9hFnK6YfNRaJSb_CrVC2C0bEoDY-d1JQ5hM1iH-JKSTcQ33abXT9vGxSAMxfiYH_Rh_jJRl87HOZb9oLp4WrdG9Dmifd7UZzLVJgx5AZloZ9rXIqxQCj_FLU77Qh3-qpJHQ3JtmXA4mA-4rDkZkY8MTTpDlagCT7z1dp5WD7r0IY-ZibMsd8aFAhp7wraENcCkPBX_4xthwUeDFXWBkqPMfcidTxpLUaMY7rbUbVRtj32X2MgJZf_bWv8yso2rMAsOUIiCo5sWD8JgzT0nwTbv_VA9ZWJS4Ob9qSJgywtxmA6TiM1LbKjcEoCnm9YMimCOVycVwT8FjDY6gFIZvXRrm2G2pwtQZ8SMEvCYJTa1k64kWiq-is7EO0wdUbW4zNq6pg_8rq6_Yi-p-VEtQdeeRIhy56yceZ9QO_ZPTIC032KvfXczmIgIGy8eAEJxUg5mpuacA6IFXsVYq2S9Nl0NhiEv9Yu3S7iHZqXAbXO02JpqAcx5vxRcCPcndDtTEOhMVe64tq6fuOoNIY6X7xgavGLbb7eDmgQFF1SHMPMwihfARR8h5Oo9bN0o4jCLVEtWNnrrt1F2-HRPsJ5ZMGbfg8Cu1piT7VFA_fydBFI


### create product
POST {{url_dev}}/product
Content-Type: application/json
x-api-key: d22131361037905b74388a3215b5078b0de51a37c3190af24b973bcc4afc4b6e75b3ffeaea5e5fcd34245d8877df0eea20d43ab2c311bd7a530dc0a817df2afc
x-client-id: 6aa3cdd741b461cb1c3eeb68
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaG9wSWQiOiI2YWEzY2RkNzQxYjQ2MWNiMWMzZWViNjgiLCJlbWFpbCI6InNob3BxdWFuZ2RldkBnbWFpbC5jb20iLCJpYXQiOjE3ODk5ODIyMzAsImV4cCI6MTc5MDE1NTAzMH0.RkfRYV4hyClm4dwiQ6SBssogZOM8iB228fD9zDQkxPyMxUhDI1XmsuOFLO_VmfydDGSdic_AEh_Ew2PMOrE_rt9ffhZYGv82ijHz-Kuk7lpQ4R3owTFoKGwMjJChtwSUQwGlEM7o34CV7bnCJA4nEfr-dzQJVHNNNVEjNKB_sxlVHWH9yJ-12qSF5rtYVwvnWHeH6vultdH_mOqwgymaKcAmNN1SfXnHy0o2qX9BOsDX3si2iMf_9TKSddqokY2w0GAzaI7jOYn6GT0UkxFK0Rv99u4PUZxRotVkYZfM_Pdchg_fgTaRWGyOyG_9AhRougHapUXUv70xwmxW-c2wHYSSGzfcivddehMnMtTb14xbGm5N5faWqtXhLv_AemvuUfDMl0RRs3VCpIr9TZp73Kbx3jXoWcw2BxjUePWr5n0LVbGILpRqC01wO4bZKoqmAM9L6Yy2b7pooNpnbetMTvMWS5Sc7c9qH20zV7JmZUmFY5Mi0KkpDivt7ruM8ajXKhj76XBxcPrEKkYbxktAtDmjNMYlf237rDBQ_ONI2y4dS57xC6luJ1qHg9EpVeHFmahAfULYP_kNt5I_2Mg55T1XJJQQ4hqtBZ-wgq2JAKz0nzDHx25jOYIcOfLi7hJoqnTqI-Q28Gef5lah3efsg4Tgsu1Lt8yz31PgMv4pYy4

{
    "product_name" : "New Jeans",
    "product_thumb" : "product_thumb",
    "product_description" : "product_description High-quality denim jeans",
    "product_price" : 608,
    "product_quantity" : 51,
    "product_type" : "Clothing",
    "product_attributes" : {
        "brand" : "adidas",
        "size" : "M",
        "material" : "Denim"
    }

}
